[build.environment]
  HUGO_VERSION = "0.105.0"

[[redirects]]
  from = "/docs/memory-safety"
  to = "https://www.memorysafety.org/docs/memory-safety"
  status = 301
  force = false

[[redirects]]
  from = "/divviup"
  to = "https://divviup.org"
  status = 301
  force = false

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
  force = false

